version: '3.8'
services:
 web:
   image: php:8.2-apache
   container_name: php-apache
   volumes:
     - ./src:/var/www/html
   ports:
     - "8080:80"
   depends_on:
     - db
 db:
   image: mysql:8.0
   container_name: mysql-db
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: rootpass
     MYSQL_DATABASE: testdb
     MYSQL_USER: user
     MYSQL_PASSWORD: userpass
   ports:
     - "3306:3306"
   volumes:
     - db_data:/var/lib/mysql
 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   container_name: phpmyadmin
   depends_on:
     - db
   environment:
     PMA_HOST: db
     PMA_PORT: 3306
   ports:
     - "8081:80"
volumes:
 db_data:
