version: '3.8'
services:
 web:
   image: php:8.2-apache
   container_name: php-app
   ports:
     - "8080:80"
   volumes:
     - ./src:/var/www/html
   depends_on:
     - db
 db:
   image: mysql:8.0
   container_name: mysql-db
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: rootpass
     MYSQL_DATABASE: myapp
     MYSQL_USER: appuser
     MYSQL_PASSWORD: apppass
   volumes:
     - db_data:/var/lib/mysql
volumes:
 db_data:
